---
version: '2'
services:
  squid:
    build:
      context: ./build-squid
    restart: always
    ports:
      - "3128:3128"
    volumes:
      - squid_cache:/var/spool/squid
      - squid_logs:/var/log/squid

volumes:
  squid_cache:
  squid_logs:
