---
version: '2'
services:
  squid:
    image: repo.tenzin.io/tlhakhan/app/squid:latest
    ports:
      - "3128:3128"
    volumes:
      - ./squid_config:/etc/squid
      - squid_cache:/var/spool/squid

volumes:
  squid_cache:
